### ISSUE TITLE
Map and Background Assets

### ISSUE THREAD

**Issue by rafaellepalmos** [rafaellepalmos/PlagueExodus#1]
Background for our levels and objects for the player to stand on.

**Comment by taechemist** [comment]
I initialised our game with 
- menu (you guys can change anytime)
- character (you guys can change anytime)
- map (1 testing map)

List of things have done so far today
- Add tilemap this map is not done yet, I just wanted to test with our
  game
- Add background with parallax effect
- Add testing charecter (only for testing), I just wanted to test the
  map
- Declare 'playLevel' globol variable to keep track of level and use it
  to generate different map
- Our game is now responsive to every screen
- Some bugs are fixed
